#!/bin/bash

pip install -e .[dev]

source_dir=$(realpath "./prompts")
target_dir=$(eval echo "~/.local/share/prompts")

if [ ! -d "$target_dir" ]; then
  mkdir -p "$target_dir"
fi

for file in "$source_dir"/*; do
  file_name=$(basename "$file")
  ln -fs "$file" "$target_dir/$file_name"
done
